import "./globals.css";
import { Saira } from "next/font/google";
import { Header } from "@/components/Header";
import { DefaultProviders } from "@/providers/default-providers";

const saira = Saira({
  weight: ["300", "400", "500", "600"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Capputeeno",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={saira.className}>
        <DefaultProviders>
          <Header />
          <body>{children}</body>
        </DefaultProviders>
      </body>
    </html>
  );
}
